name: Test

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: |
          cd extension && yarn && cd ..
          cd server && yarn && cd ..
      - name: Execute tests
        run: |
          cd extension && yarn test && cd ..
          cd server && yarn test && cd ..
