name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: |
          cd extension && npm i && cd ..
          cd server && npm i && cd ..
      - name: Execute tests
        run: |
          cd extension && npm test && cd ..
          cd server && npm test && cd ..
